language: python, node_js
python:
    - 3.6

node_js:
    - 10

addons:
    apt:
        packages:
            - mecab
            - mecab-ipadic
            - mecab-utils
            - mecab-ipadic-utf8
            - libmecab-dev

install:
    - pip install --user -r backend-aetam/requirements.txt
    - cd frontend-aetam && make install && cd -

cache:
    pip: true
    directories:
        - node_modules

script:
    - cd backend-aetam && make test && cd -
    - cd frontend-aetam && make test && cd -
