language: python, node_js
python:
    - 3.6

node_js:
    - 10

install:
    - pip install --user -r backend-aetam/requirements.txt
    - cd frontend-aetam && make install && cd -

cache:
    pip: true
    directories:
        - node_modules

script:
    - cd backend-aetam && make test && cd -
    - cd frontend-aetam && make test && cd -
