---
- name: clone pyenv installer
  shell: |
    git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    echo 'export PATH="${PYENV_ROOT}/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile

- name: install python depend package
  apt: name="{{item}}" state=present update_cache=True
  with_items:
    - libssl-dev 
    - libbz2-dev 
    - libreadline-dev
    - libsqlite3-dev

- name: source bash_profile
  command: source ~/.bash_profile

- name: install python
  command: pyenv install 3.6.4

- name: enable python
  command: pyenv global 3.6.4


- name: pip install opencv
  command: pip install opencv-pythona matplotlib

- namne: pip install flask
  command: pip install Flask
