---
- name: clone pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: /home/{{ ansible_ssh_user }}/.pyenv
    update: False
  register: pyenv
  become: True

- name: settings pyenv
  lineinfile:
    path: /home/{{ ansible_ssh_user }}/.bashrc
    state: present
    create: True
    line: "{{item}}"
  with_items:  # insert line is reverse
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="${PYENV_ROOT}/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: install python depend package
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev

- name: source python
  shell: bash -lc "sudo /home/vagrant/.pyenv/bin/pyenv install 3.6.4 && sudo /home/vagrant/.pyenv/bin/pyenv global 3.6.4"
  become_user: vagrant
  when: pyenv is changed

- set_fact: ansible_python_interpreter=/home/vagrant/.pyenv/shims/python

- name: pip install opencv
  pip:
    name: "{{ item }}"
  with_items:
    - opencv-python
    - matplotlib

- name: pip install flask
  pip:
    name: Flask
